config/routes.rb
FirstApp::Application.routes.draw do
  resources :microposts, :only => [:create, :destroy]
  resources :users  do
    member do
      get :following, :followers
    end
  end
  resources :sessions,  :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
    
  match '/signup',    :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'
  
  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/help',      :to => 'pages#help'
  root    :to => 'pages#home'
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize( object.errors.count, "error")%>
			prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
			from being saved:
		</h2>
		<p>There were problems with the following fields: </p>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<br/>
<br/>
<br/>
<% unless @feed_items.nil? or @feed_items.empty? %>
   <div>
    <%= page_entries_info @feed_items , :entry_name => 'item'  %>
    </div>
	<table class="micorposts" summary="User microposts">
		<%= render :partial => 'shared/feed_item',  :collection => @feed_items %>
	</table>
	<%= will_paginate @feed_items %>
<% end%>

app/views/shared/_feed_item.html.erb
<tr>
	<td class="gravatar">
		<%= link_to gravatar_for( feed_item.user), feed_item.user %>
	</td>
	<td class="micropost">
		<span class="user">
			<%= link_to feed_item.user.name, feed_item.user %>
		</span>
		<span class="content"><%= wrap( feed_item.content) %></span>
		<span class="timestamp">
			Posted <%= time_ago_in_words( feed_item.created_at) %> ago.
		</span>	
		
	</td>
	<% if current_user?( feed_item.user)%>
	<td>
		<%= link_to "Delete", feed_item, :method => :delete, :confirm => "You sure?", :title => feed_item.content %>
		
	</td>
	<% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%-#= f.text_area  :content,  :onKeyUp =>"return taCount(this,'myCounter')",	  :onKeyDown =>"return taCount(this,'myCounter')"    -%>
		<%= f.text_area  :content, :onKeyUp =>"countLeft(this, this.form.counter, 140)"  %>
	</div>
	
	<input type="text" name="counter" size="3" value="140" readonly disabled>characters remaining 	
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>


  <script  language="JavaScript">
 // function parameters are: field - the string field, count - the field for remaining
//  characters  number and max - the maximum number of characters  
 function countLeft(field, count, max) {
 	var remaining = max - field.value.length;
	//We do this because different browsers and servers handle new lines differently.
	//Internet Explorer and Opera say a new line is \r\n
	//Firefox and Safari say a new line is just a \n
	//ASP.NET seems to convert any plain \n characters to \r\n, which leads to counting issues
 	var value = field.value.replace(/\u000d\u000a/g,'\u000a').replace(/\u000a/g,'\u000d\u000a');

	 // if the length of the string in the input field is greater than the max value, trim it 
	 if (remaining < 0){
		 //alert( field.value);
		 // field.value = value.substring(0, max);
		 value =  value.substring(0, max);
		  field.value = value; // value.substring(0, max);
		  field.setSelectionRange(max, max);
		  remaining = max - field.value.length;
	}
	 // calculate the remaining characters  
	 count.value = remaining; //max - field.value.length;
 }
 </script>	

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
	<table summary="User stats">
		<tr>
			<td>
				<a href="<%= following_user_path( @user) %>">
					<span id="following" class="stat">
					<%= @user.following.count %> following
					</span>
				</a>
			</td>
			<td>
				<a href="<%=  followers_user_path(@user) %>">
					<span id="followers" class="stat">
						<%= pluralize( @user.followers.count, "follower") %>
					</span>
				</a>	
			</td>
		</tr>
	</table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
	<a href="<%= user_path( current_user)%>">
		<%= gravatar_for current_user,  :size => 30 %>
		<span class="user_name">
			<%= current_user.name %>
		</span>
		<span class="micorposts">
			<%= pluralize( current_user.microposts.count, "micropost") %>
		</span>
	</a>
</div>